5.1 – Linear Regression

In [7]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [8]:

df = pd.read_csv("../data/processed/medical_insurance_processed.csv")

In [9]:
X = df.drop(columns=["annual_medical_cost"])
y = df["annual_medical_cost"]

In [10]:
numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

C:\Users\HP\AppData\Local\Temp\ipykernel_11288\2075704492.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(

In [11]:
numerical_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [13]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [14]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(80000, 82)
(20000, 82)

In [15]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train_processed, y_train)

LinearRegression()

In [16]:
y_pred = linear_model.predict(X_test_processed)

In [17]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

In [18]:
print("=" * 40)
print("Linear Regression Performance")
print("=" * 40)

print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

========================================
Linear Regression Performance
========================================
MAE  : 319.91
MSE  : 330476.83
RMSE : 574.87
R²   : 0.9664

In [19]:
results = y_test.reset_index(drop=True).to_frame(name="Actual")
results["Predicted"] = y_pred


results.head(10)

    Actual    Predicted
0  1640.86  2089.777083
1  2306.61  2455.354536
2  1015.03   828.705009
3  1136.82   945.592555
4  3990.84  4438.464602
5  2518.82  2486.155638
6  1180.51  1621.208823
7   571.16   760.086972
8   771.25   891.329233
9  8863.49  7760.231690

In [20]:
results["Residual"] = (
    results["Actual"] - results["Predicted"]
)

results.head()

    Actual    Predicted    Residual
0  1640.86  2089.777083 -448.917083
1  2306.61  2455.354536 -148.744536
2  1015.03   828.705009  186.324991
3  1136.82   945.592555  191.227445
4  3990.84  4438.464602 -447.624602

In [21]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("=" * 40)
print("Linear Regression Performance")
print("=" * 40)

print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

========================================
Linear Regression Performance
========================================
MAE  : 319.91
MSE  : 330476.83
RMSE : 574.87
R²   : 0.9664

5.2 – Decision Tree Regressor

In [22]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

In [23]:
decision_tree = DecisionTreeRegressor(
    random_state=42
)

In [24]:
decision_tree.fit(X_train_processed, y_train)

DecisionTreeRegressor(random_state=42)

In [25]:
y_pred_dt = decision_tree.predict(X_test_processed)

In [26]:
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_test, y_pred_dt)

In [27]:
print("=" * 40)
print("Decision Tree Performance")
print("=" * 40)

print(f"MAE  : {mae_dt:.2f}")
print(f"MSE  : {mse_dt:.2f}")
print(f"RMSE : {rmse_dt:.2f}")
print(f"R²   : {r2_dt:.4f}")

========================================
Decision Tree Performance
========================================
MAE  : 8.48
MSE  : 20810.88
RMSE : 144.26
R²   : 0.9979

In [28]:
dt_results = y_test.reset_index(drop=True).to_frame(name="Actual")
dt_results["Predicted"] = y_pred_dt

dt_results.head(10)

    Actual  Predicted
0  1640.86    1641.02
1  2306.61    2308.77
2  1015.03    1013.41
3  1136.82    1136.85
4  3990.84    4013.00
5  2518.82    2523.79
6  1180.51    1180.58
7   571.16     570.94
8   771.25     771.16
9  8863.49    8839.73

In [29]:
dt_results["Residual"] = (
    dt_results["Actual"] - dt_results["Predicted"]
)

dt_results.head()

    Actual  Predicted  Residual
0  1640.86    1641.02     -0.16
1  2306.61    2308.77     -2.16
2  1015.03    1013.41      1.62
3  1136.82    1136.85     -0.03
4  3990.84    4013.00    -22.16

5.3 – Random Forest Regressor

In [30]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

In [31]:
random_forest = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [32]:
random_forest.fit(X_train_processed, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [33]:
y_pred_rf = random_forest.predict(X_test_processed)

In [34]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

In [35]:
print("=" * 40)
print("Random Forest Performance")
print("=" * 40)

print(f"MAE  : {mae_rf:.2f}")
print(f"MSE  : {mse_rf:.2f}")
print(f"RMSE : {rmse_rf:.2f}")
print(f"R²   : {r2_rf:.4f}")

========================================
Random Forest Performance
========================================
MAE  : 7.67
MSE  : 16036.08
RMSE : 126.63
R²   : 0.9984

In [36]:
rf_results = y_test.reset_index(drop=True).to_frame(name="Actual")
rf_results["Predicted"] = y_pred_rf

rf_results.head(10)

    Actual  Predicted
0  1640.86  1641.0880
1  2306.61  2307.3346
2  1015.03  1015.2094
3  1136.82  1135.8592
4  3990.84  4003.8472
5  2518.82  2520.8307
6  1180.51  1180.8374
7   571.16   570.6347
8   771.25   771.0929
9  8863.49  8843.7811

In [37]:
rf_results["Residual"] = (
    rf_results["Actual"] - rf_results["Predicted"]
)

rf_results.head()

    Actual  Predicted  Residual
0  1640.86  1641.0880   -0.2280
1  2306.61  2307.3346   -0.7246
2  1015.03  1015.2094   -0.1794
3  1136.82  1135.8592    0.9608
4  3990.84  4003.8472  -13.0072